/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradlex.archetypes;

import org.apache.commons.io.FileUtils;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class GradleArchetypesPluginFunctionalTest {

    // we use the build directory instead of @TmpDir to make it easier to manually inspect outcome
    File projectDir;
    File templateRepoDir;

    @BeforeEach
    void setup(TestInfo testInfo) throws IOException {
        String testId = testInfo.getTestClass().get().getName() + "." + testInfo.getTestMethod().get().getName();
        projectDir = new File(System.getProperty("testRootDir"), testId + "/project");
        templateRepoDir = new File(System.getProperty("testRootDir"), testId + "/templateRepo");
        FileUtils.deleteDirectory(projectDir);
        FileUtils.deleteDirectory(templateRepoDir);
        projectDir.mkdirs();
        templateRepoDir.mkdirs();
    }

    @Test
    @DisplayName("Can generate project from template repository")
    void canGenerateProjectFromTemplateRepository() throws IOException {
        String settingsScriptTemplate = "<#GradleTemplate>\n" +
                "file=settings.gradle<#if dsl =='kotlin'>.kts</#if>\n" +
                "</#GradleTemplate>\n" +
                "\n" +
                "rootProject.name = \"${projectName}\"";
        String templateOptions = "{\n" +
                "    \"name\": \"basic\",\n" +
                "    \"questions\": [\n" +
                "        {\n" +
                "            \"type\": \"string\",\n" +
                "            \"name\": \"projectName\",\n" +
                "            \"question\": \"Project Name\",\n" +
                "            \"default\": \"example\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"type\": \"choice\",\n" +
                "            \"name\": \"dsl\",\n" +
                "            \"question\": \"DSL\",\n" +
                "            \"choices\": {\n" +
                "                \"kotlin\": \"Kotlin\",\n" +
                "                \"groovy\": \"Groovy\"\n" +
                "            }\n" +
                "        }\n" +
                "    ]\n" +
                "}⏎";
        writeString(new File(templateRepoDir, "settings.gradle"), settingsScriptTemplate);
        writeString(new File(templateRepoDir, "templateOptions.json"), templateOptions);

        // setup:
        String pluginRepo = System.getProperty("pluginRepo");
        String initGradleText = "                                                          \n" +
                "initscript {                                                              \n" +
                "    repositories {                                                        \n" +
                "        mavenCentral()                                                    \n" +
                "        maven {                                                           \n" +
                "             url ='" + pluginRepo + "'                                    \n" +
                "        }                                                                 \n" +
                "    }                                                                     \n" +
                "                                                                          \n" +
                "    dependencies {                                                        \n" +
                "       classpath 'org.gradlex:plugin:0.0.1'                               \n" +
                "       classpath 'org.freemarker:freemarker:2.3.31'                       \n" + // TODO dependencies should be packaged with the plugin
                "       classpath 'org.eclipse.jgit:org.eclipse.jgit:5.7.0.202003110725-r' \n" + // TODO dependencies should be packaged with the plugin
                "       classpath 'commons-io:commons-io:1.4'                              \n" + // TODO dependencies should be packaged with the plugin
                "       classpath 'com.fasterxml.jackson.core:jackson-core:2.13.3'         \n" + // TODO dependencies should be packaged with the plugin
                "       classpath 'com.fasterxml.jackson.core:jackson-annotations:2.13.3'  \n" + // TODO dependencies should be packaged with the plugin
                "       classpath 'com.fasterxml.jackson.core:jackson-databind:2.13.3'     \n" + // TODO dependencies should be packaged with the plugin
                "    }                                                                     \n" +
                "}                                                                         \n" +
                "                                                                          \n" +
                "rootProject {                                                             \n" +
                "    apply plugin: org.gradlex.archetypes.GradleArchetypesPlugin           \n" +
                "}                                                                         \n" +
                "                                                                          \n";

        writeString(new File(projectDir, "init.gradle"), initGradleText);

        // when:
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("init", "--init-script", "init.gradle", "--template", templateRepoDir.getAbsolutePath(), "-s");
        runner.withProjectDir(projectDir);
        runner.build();

        // then:
        File settingsFile = new File(projectDir, "settings.gradle.kts");
        assertTrue(settingsFile.exists());
        assertEquals(FileUtils.readFileToString(settingsFile), "\nrootProject.name = \"example\"\n");
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
