/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradlex.archetypes;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;

import static org.junit.jupiter.api.Assertions.assertTrue;

class GradleArchetypesPluginFunctionalTest {
    @TempDir
    File projectDir;

    private File getBuildFile() {
        return new File(projectDir, "build.gradle");
    }

    private File getSettingsFile() {
        return new File(projectDir, "settings.gradle");
    }

    @Test void canRunTask() throws IOException {
        String pluginRepo = System.getProperty("pluginRepo");

        String initGradleText = "\n" +
                "initscript {                                                    \n" +
                "    repositories {                                              \n" +
                "        maven {                                                 \n" +
                "             url ='" + pluginRepo + "'                          \n" +
                "        }                                                       \n" +
                "    }                                                           \n" +
                "                                                                \n" +
                "    dependencies {                                              \n" +
                "       classpath 'org.gradlex:plugin:0.0.1'                     \n" +
                "    }                                                           \n" +
                "}                                                               \n" +
                "                                                                \n" +
                "rootProject {                                                   \n" +
                "    apply plugin: org.gradlex.archetypes.GradleArchetypesPlugin \n" +
                "}                                                               \n" +
                "                                                                \n";

        writeString(new File(projectDir, "init.gradle"), initGradleText);

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        //runner.withPluginClasspath();
        runner.withArguments("init", "--init-script", "init.gradle");
        runner.withProjectDir(projectDir);
        BuildResult result = runner.build();

        // Verify the result
        assertTrue(result.getOutput().contains("Howdy"));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
